### ISSUE TITLE
Client Namespaces do not appear to work correctly

### ISSUE THREAD

**Issue by thessem** [zyxar/socketio#4]
I have the following code
```
err := client.Dial(
	"<URL>"
	http.Header{},
	engine.WebsocketTransport,
	socket.DefaultParser,
)
if err != nil {
	panic(err)
}

err := client.Emit("/namespace", "message", func(msg string) {
	log.Println("Client.Emit", msg)
})
if err != nil {
	panic(err)
}
```

Upon running the second error becomes `namespace unavailable`. I was wondering whether this was a bug in the code, or whether I am using the library wrong. 

Thanks

**Comment by thessem** [comment]
I also don't appear to be able to connect to a namespace, which I am able to do with the Socket.IO JS client. Again, I'm not sure if that's an as-of-yet unwritten feature or if I'm using the library wrong

**Comment by zyxar** [comment]
Hi  @thessem, did you open a namespace on  server side, like below example?
https://github.com/zyxar/socketio/blob/master/example_test.go#L94

**Comment by thessem** [comment]
Thanks for getting back to me. I am not using https://github.com/zyxar/socketio server code, my server is https://github.com/googollee/go-socket.io. The server definitely has namespaces working correctly as they are usable using the https://socket.io/ (v1.4) client library.

If I get some time this week I will attempt an end-to-end example. Would you still consider it a bug if it does not replicate using https://github.com/zyxar/socketio as both the client and the server?

**Comment by zyxar** [comment]
I guess so.
Will look into this later :)

**Comment by thessem** [comment]
I suspect this is a socket.io version thing.

My use case here is that I'm using your library to unit test an existing go-socket.io server. My work around was to set the namespace in each test for both the client and the server to "/" in which case everything seems to work. So, this isn't a production bug for me, and I have an at least an inelegant workaround.

Also, I'd just like to say thanks for your library, I tried a few other golang socket.io client libraries and none of them even slightly worked for my usecase.

**Comment by thessem** [comment]
Closing because I no longer use this library (changed jobs)
