### ISSUE TITLE
Namespace not working

### ISSUE THREAD

**Issue by wukaMM** [zyxar/socketio#7]
Hi,

I am using the example code like this:
    

```
server, _ := socketio.NewServer(time.Second*25, time.Second*5, socketio.DefaultParser)
server.Namespace("/").
        OnConnect(func(so socketio.Socket) {
            log.Println("connected:", so.RemoteAddr(), so.Sid(), so.Namespace())
        }).
        OnDisconnect(func(so socketio.Socket) {
            log.Printf("%v %v %q disconnected", so.Sid(), so.RemoteAddr(), so.Namespace())
        }).
        OnError(func(so socketio.Socket, err ...interface{}) {
            log.Println("socket", so.Sid(), so.RemoteAddr(), so.Namespace(), "error:", err)
        }).
        OnEvent("join", func(so socketio.Socket, data string) {
            log.Println(data)
        })
```

This works very well, but if the client request a connection like "http://localhost:8081/test", and my server side likes this

    server, _ := socketio.NewServer(time.Second*25, time.Second*5, socketio.DefaultParser)
    server.Namespace("/test").
        OnConnect(func(so socketio.Socket) {
            log.Println("connected:", so.RemoteAddr(), so.Sid(), so.Namespace())
        }).
        OnDisconnect(func(so socketio.Socket) {
            log.Printf("%v %v %q disconnected", so.Sid(), so.RemoteAddr(), so.Namespace())
        }).
        OnError(func(so socketio.Socket, err ...interface{}) {
            log.Println("socket", so.Sid(), so.RemoteAddr(), so.Namespace(), "error:", err)
        }).
        OnEvent("join", func(so socketio.Socket, data string) {
            log.Println(data)
        })

But it doesn't work, any suggestions? Thank you.

**Comment by wukaMM** [comment]
Hi, 
I find out the reason.
When the client side is 

```
const socket = io("http://127.0.0.1:8081/test", { 
        transport : ['websocket'],
        autoConnect: true,
        query: {
          auth: '1'
        }
      });
```
Both namespace and query are included, and then, the client can't connect to the server.

If there is only namespace or query included, the connect runs well.

Any suggestions? Thank you.

**Comment by wukaMM** [comment]
And also, my socket.io client is 2.1.1, which convert the namespace from '/test' to '/test?auth=1'. While the client 1.4.0 is correct and works well.
How can I figure this out by using version 2.1.1 ?
Please help, thank you.

**Comment by zyxar** [comment]
It's fixed now. Previously the parser failed to extract the exact namespace value while the query was present.
